FROM python:3.12-slim

WORKDIR /down-dog

RUN pip install --no-cache-dir \
    --index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    --trusted-host pypi.tuna.tsinghua.edu.cn \
    "boto3==1.35.36" \
    "python-dotenv==1.0.1"

COPY s3.py .
COPY "./Images" "./Images"

CMD ["python", "s3.py"]
