#!/usr/bin/env python3
"""Validate that a commit message follows the Conventional Commits spec."""

import re
import sys

CONVENTIONAL_TYPES = frozenset(
    ["feat", "fix", "build", "chore", "ci", "docs", "style", "refactor", "perf", "test"]
)

# header := type [scope] [breaking] : subject
HEADER_RE = re.compile(
    r"^(?P<type>[a-z]+)(\((?P<scope>[^()\r\n]+)\))?(?P<breaking>!)?: (?P<subject>.+)$"
)

# Subject must be present and must not end with a period.
SUBJECT_RE = re.compile(r"^\S.*[^.]$")


def main() -> int:
    message_file = sys.argv[1]
    with open(message_file, encoding="utf-8") as f:
        content = f.read()

    first_line = content.strip().splitlines()[0].strip()

    # Merge and revert commits are generated by tooling, not the author.
    if first_line.startswith(("Merge ", "Revert ")):
        return 0

    match = HEADER_RE.match(first_line)
    if not match:
        print(
            "Invalid commit message format.\n"
            "Expected Conventional Commits, e.g.:\n"
            "  feat: add new feature\n"
            "  fix(auth): fix login flow\n"
            "  feat!: breaking change\n"
            f"Got: {first_line!r}"
        )
        return 1

    commit_type = match.group("type")
    if commit_type not in CONVENTIONAL_TYPES:
        allowed = ", ".join(sorted(CONVENTIONAL_TYPES))
        print(f"Unknown commit type {commit_type!r}. Allowed types: {allowed}.")
        return 1

    if not SUBJECT_RE.match(match.group("subject")):
        print("Subject must be non-empty and must not end with a period.")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
